### ISSUE TITLE
R CMD check fails with dev version of tidyr

### ISSUE THREAD

**Issue by hadley** [MansMeg/markmyassignment#103]
*   checking whether package ‘markmyassignment’ can be installed ... WARNING
    ```
    Found the following significant warnings:
      Warning: replacing previous import ‘checkmate::expect_vector’ by ‘testthat::expect_vector’ when loading ‘markmyassignment’
    See ‘/Users/hadley/Documents/devtools/testthat/revdep/checks.noindex/markmyassignment/new/markmyassignment.Rcheck/00install.out’ for details.
    ```

Because, I'm guessing, you're doing `@import testthat`.

**Comment by MansMeg** [comment]
Thanks!

**Comment by hadley** [comment]
Can you please submit a fix to CRAN?

**Comment by MansMeg** [comment]
Hi! 

Sorry for my delay (due to easter). This package depends on both testthat and checkmate and I do not see an easy way to solve it in any other way. Although I do not think this warning message is a problem at all. Can it just be ignored?

**Comment by hadley** [comment]
I have submitted to CRAN, so you'll like hear complaints from them in the near future. It's definitely a problem, and you can solve it by not importing all of testthat and checkmate (which is generally good practice anyway).

To be clear: it's not the use of `Imports:` in DESCRIPTION that's the problem, it's the use of `imports()` in your [NAMESPACE](https://github.com/MansMeg/markmyassignment/blob/master/NAMESPACE#L19-L23).

**Comment by MansMeg** [comment]
Ah. Sorry, I missunderstood. Yes, will fix that.

**Comment by MansMeg** [comment]
Fixed.
