### ISSUE TITLE
Check CRAN questions

### ISSUE THREAD

**Issue by MansMeg** [MansMeg/markmyassignment#19]
Dear CRAN package maintainer,

We email all CRAN maintainers periodically to check that the email
address is still active and to remind them of the CRAN policies at
<http://CRAN.R-project.org/web/packages/policies.html>.

Changes to those policies in the last 4 months are given below.

Please check whether your maintainer address needs updating (in
particular in case you moved, or received multiple copies of this
message).

Please also make sure that in your package DESCRIPTION file,

* The Title field uses title case and does not end a period.  It should
  not repeat the package name, and should be on one line and preferably
  no more than 65 chars.

* The Description field really give a comprehensive description of what
  the package does, and avoids redundancies such as "This package ..."
  or "An R package for ...".

Please do *not* reply to this message.

Best,
-k

**Comment by MansMeg** [comment]
Run check as CRAN in R-Studio.
Set Check package --as-cran

**Comment by oscpe436** [comment]
Är \donttest som finns i dokumentationen ett problem för CRAN?

**Comment by MansMeg** [comment]
Det beror på, vad får du för meddelande? Är det en warning eller en NOTE?

**Comment by oscpe436** [comment]
Det bara nämns men räknas varken som warning eller NOTE.
https://travis-ci.org/MansMeg/markmyassignment/builds/98287949

**Comment by MansMeg** [comment]
Ah! Vi behöver lägga till att även testa donttest. På cran kommer de köra det som ligger under donttest. Enklast kanske är att göra om till dontrun eller ta bort donttest. Vad tror du är bäst?

**Comment by oscpe436** [comment]
Det som ligger det fungerar efter några mindre ändringar. Men kommer mappen /extdata att följa med och fungerar exemplena på alla plattformar?

**Comment by MansMeg** [comment]
De ska fungera på alla plattformar, dock är jag inte 100% på detta. När de gör sina tester på CRAN så bygger de paketet för ett stort antal olika operativsystem så då kommer vi annars få information om det failar på något särskilt operativsystem.

Jag kan bara bygga på MacOS och Travis kör med Linux så de systemen bör vara säkrade. Vad kör du på?

**Comment by oscpe436** [comment]
Okej. Men då kanske det är bra att lämna det kvar så att de får köra det.
Jag har en Windowsdator så vi täcker upp en hel del.

**Comment by MansMeg** [comment]
Topp! Då täcker vi upp de tre stora. Finkar det här bör resten också fungera.
