### ISSUE TITLE
Fix fakeglobal environment for marking files

### ISSUE THREAD

**Issue by MansMeg** [MansMeg/markmyassignment#31]
On 10/02/2015 3:30 AM, Måns Magnusson wrote:
> Thanks,
>
> But the problem would still be that testthat assignments the students work with would follow the search path back to the global environment if the student have assigned A <- 2 in file but have 'a' in the global environment and the unit test tests for 'a' rather than 'A'?

The global environment would not be seen if the evaluation took place in
"fakeglobal".  The global environment comes before the search path, not
after.

Duncan Murdoch

>
>
> Skickat från min iPhone
>
>> 8 feb 2015 kl. 21:46 skrev Duncan Murdoch <murdoch.duncan@gmail.com>:
>>
>>> On 08/02/2015 12:16 PM, Måns Magnusson wrote:
>>> Hi!
>>>
>>> The problem is that the test environment inherits from the global
>>> environment.
>>> See https://github.com/hadley/testthat/blob/master/R/test-files.r
>>>
>>> The students labs are simply an R script file. Say that they have an
>>> assignment to calculate sqrt(2) and store it in variable a. In the same
>>> session they should be able to test the script file when they are done
>>> (using a function mark_my_file() in the package). This function will
>>> call the testthat tests.
>>>
>>> Say that I have two unit tests. One tests if an object called 'a' exists
>>> in the file and the second one tests if 'a' is sqrt(2) and return
>>> messages to the students pointing them in the right direction (ie 'a' is
>>> missing or is wrong).
>>>
>>> The problem is the if the student have an other object 'a' in the global
>>> environment but do not create 'a' in their R script file. In this case
>>> testthat test will follow the search path and find the object in the
>>> global environment and return the wrong (or none) error message due to
>>> the global environment.
>>>
>>> The only way around this problem is to temporarily store the global
>>> environment, clean it and run the tests, and the reload the old global
>>> environment. But this solution will not be publishable on CRAN.
>>>
>>> I hope this can clarify the problem.
>>
>> But you don't need to use test_env():  it's the default for a number of
>> other functions, but your function could replace them with something else.
>>
>> For example, if you want an environment that is like the global
>> environment but empty, simply create a new one, whose parent is the
>> parent of globalenv().  For example:
>>
>> fakeglobal <- new.env(parent = parent.env(globalenv()))
>>
>> source("studentfile.R", local = fakeglobal)
>>
>> test_file("yourtests.R", local = fakeglobal)
>>
>> If the student code (or yours) needs to load packages, this code won't
>> see them, but there are workarounds for that too.  The main thing is
>> that the student results will be in fakeglobal, and nothing else will be.
>>
>> Duncan Murdoch
>>
>>
>>> Kind regards
>>> Måns
>>>
>>>
>>>
>>> Skickat från min iPhone
>>>
>>> 8 feb 2015 kl. 16:46 skrev Duncan Murdoch <murdoch.duncan@gmail.com
>>> <mailto:murdoch.duncan@gmail.com>>:
>>>
>>>>> On 08/02/2015 8:22 AM, Måns Magnusson wrote:
>>>>> Hi!
>>>>>
>>>>> Im currently developing an R package to automatically give students
>>>>> feedback on programming assignments in R. I use the testthat package
>>>>> as an
>>>>> engine for the unit testing and do a wrapper to make the automatic
>>>>> marking
>>>>> easy for the students.
>>>>>
>>>>> One function (called mark_my_file() ) will mark the students lab file
>>>>> using
>>>>> testthat tests and a new (simple) reporter. The problem is that I need to
>>>>> do the marking of the lab with an empty global environment (due to the
>>>>> testthat package).
>>>>>
>>>>> So my first thought was to:
>>>>> 1) store the global environement in the temporary directory as an
>>>>> .Rdata-file
>>>>> 2) clean the global environment
>>>>> 3) run the tests
>>>>> 4) clean the global environment (from the student lab file)
>>>>> 5) reload the old global environment
>>>>>
>>>>> But the problem is that it is not possible to publish packages on
>>>>> CRAN that
>>>>> modifies the global environment.
>>>>>
>>>>> Is there anyone that have any solutions/ideas to this problem?
>>>>>
>>>>> The package can be found here:
>>>>> https://github.com/MansMeg/markmyassignment
>>>>
>>>> I don't think that testthat requires you to use the global environment.
>>>> Could you give some example code to show where you think you need it?
>>>> Someone could probably come up with a different formulation.
>>>>
>>>> Duncan Murdoch
>>

**Comment by MansMeg** [comment]
To make the fake global environment, this is only nessecary in the mark_my_file() function. mark_my_assignement should read from the global environment.

**Comment by MansMeg** [comment]
Fake global should have the same parent environemnet as the global environment.

**Comment by MansMeg** [comment]
Klipper in ditt mejl här:

Jag kan inte riktigt se något problem med mark_my_assignment eller mark_my_file nu. Båda verkar fungera och göra det de ska men ingen av dem verkar påverka Global Environment eftersom de använder run_test_suite som läser in objekten i ett eget environment. Så jag vet inte riktigt var jag ska sätta in fakeglobal här eller om det ens behövs.

**Comment by MansMeg** [comment]
Jag har kollat lite snabbt. I mark_my_file() görs dels en koll efter global environment:
```
  if(length(ls(.GlobalEnv)) > 0) stop("Clean global environment before running tests on file.", call. = FALSE)
```

Så detta behöver tas bort.

Sedan skapas en test_env(). I beskrivningen av denna funktion framgår:
```
We use a new environment which inherits from globalenv. In an ideal world, we'd avoid putting the global environment on the search path for tests, but it's not currently possible without losing the ability to load packages in tests.
```

D.v.s. den har global som parent environment. Ovan framgår att vi behöver skapa en environment som har global env parent environment som parent invironment. Det gör att man inte kan läsa in paket i testerna, men det är ok just nu.

**Comment by oscpe436** [comment]
Det sista testet stämmer nu inte; att bara använda parametern mark_file i mark_my_assignment resulterar inte längre i något error utan fungerar i princip som mark_my_file. Är det okej eller ska testet resultera i ett error?

**Comment by MansMeg** [comment]
Tanken är ju att vi ska försöka sära på dessa två funktioner så det bör nog resultera i ett error/Depricated (tror den använder ```.Depricated```) så går det att ändra testet till en depricated är ju det bästa.

**Comment by oscpe436** [comment]
Den ska alltså stoppa funktionen och inte bara ge en varning?

**Comment by MansMeg** [comment]
Ja, den bör stoppas. Dock innebär detta att markmydir kanske failar och behöver fixas.
