### ISSUE TITLE
Handle packages in assignments

### ISSUE THREAD

**Issue by MansMeg** [MansMeg/markmyassignment#42]
Add packages to yml file.
Check that these packages are installed when the assignment is added.

Load these packages before tests are run.

**Comment by oscpe436** [comment]
Ska paketen vara skrivna som "listelement" i yml-filerna som tasks och mandatory är nu, med en på varje rad?

**Comment by MansMeg** [comment]
Hmmm. Tror det bästa är om det bara är en rad och man anger paketet som en lista:
```
fruits: ['Apple', 'Orange', 'Strawberry', 'Mango']
```

**Comment by MansMeg** [comment]
Du har helt rätt gällande att personer behöver lära sig att de måste använda paket på ett korrekt sätt, så den borde inte läsa in dessa automatiskt. Den borde bara kontrollera om paketen är installerade och om de inte är det skapa en varning när set_environment läses in.

Problemet som dock behöver lösas är att paketen behöver läsas in innan vi skapar miljön för att köra markmyfile() i. Om paketen läses in vid source kommer de hamna efter parent.env(.Globalenv) i sökvägen och kommer därför inte att hittas.

**Comment by oscpe436** [comment]
Är denna avklarad?
Som det är nu så behöver paketen vara inlästa för att man ska kunna köra MMF eller MMD, annars säger de ifrån. Om de är inlästa så gör det inget om de läses in igen.

**Comment by MansMeg** [comment]
Topp!
