### ISSUE TITLE
Handling circular calls in mark_my_file()

### ISSUE THREAD

**Issue by MansMeg** [MansMeg/markmyassignment#48]
``ìnstall.packages```, ```data``` and ```set_assignments```.

These functions should not be evaluated when mark_my_file is called. This needs to be handled, maybe by commenting out these lines in the student file. Now they are just forbidden.

The data() function has global env as default so this needs to be commented out.

**Comment by MansMeg** [comment]
See #41

**Comment by oscpe436** [comment]
Följande funktioner körs nu inte om de finns i koden:
mark_my_assignment, mark_my_dir, set_assignment, mark_my_file, install.packages och install_github. Finns det fler?

När de gäller data() så har jag inte kommit på något bra. Först tänkte jag byta ut data() mot en ny funktion som läser in till rätt environment men jag har inte fått den att fungera. Det enda alternativet jag ser är att byta ut en source() mot en ny funktion som går igenom koden rad för rad men mark_my_file() börjar redan att bli långsam.
Men jag tror att dataset även läses in från yml-filen när testen görs och det sköts av testthatfunktioner som är lite svåra att ändra på.

**Comment by MansMeg** [comment]
Ja, det låter som att det vettigaste är att detta data läses in när vi kör testfunktionerna. Då kommer allt lösa sig automatiskt om jag tänker rätt. Dataseten kommer alltid finnas om de finns i sökvägen, så då borde det vara lugnt.

Har du prövat att köra på era labbar och rätta mark_my_dir(). Finns det några andra problem som verkar dyka upp?

**Comment by oscpe436** [comment]
Jag förstod inte helt..
Som det är nu så finns det inga problem med att se dataseten eftersom de ligger i package:datasets som ligger en bit upp i search()-pathen men seten dyker också upp i Global Environment. Men det kanske inte behövde lösas om det beror på elevernas egna kod eller vad läraren har i sina testfiler?

**Comment by MansMeg** [comment]
Nej, precis. Då kan man bara köra på. Vi bör nog notera, alt. skriv ut vilka funktioner som ignoreras när man kör mark_my_file(). Så läraren vet det och lägger in det i filerna. Jag tror att det bästa isf är att vi också ignorerar att köra data()-anrop. Det är väl bara att lägga till det i vektorn?

**Comment by oscpe436** [comment]
Okej. data() ignoreras nu också och allting fungerar ändå.

Funktionen skriver nu ut vilka "statements" som ignoreras men dock inte vilken rad de står på i labbfilen eftersom man skulle behöva slöa ner koden då.

**Comment by MansMeg** [comment]
Grymt! Då kör vi på detta.
