### ISSUE TITLE
Fix mark_my_dir

### ISSUE THREAD

**Issue by MansMeg** [MansMeg/markmyassignment#50]

**Comment by oscpe436** [comment]
Svar på fråga i #48.
mark_my_dir() verkar fungera som det ska men jag har inte kunnat köra hela lab 2 rakt igenom eftersom min dator får spader av faktoriseringsuppgiften. Men jag fick till slut ett resultat även för den uppgiften även om datorn hade fått slut på minne flera gånger om.
Men å andra sidan så fungerar parametern tasks bra.

**Comment by MansMeg** [comment]
Toppen! Det fel du får måste vara pga attstudenterna inte implementerat detta särtskilt effektivt misstänker jag. Då tycker jag vi stänger denna just nu så kan vi öppna om det skulle behöva fixas framöver.
