### ISSUE TITLE
Change from deprecated url_success

### ISSUE THREAD

**Issue by oscpe436** [MansMeg/markmyassignment#77]
In assert_function_arguments_in_API.
From update in _httr_.

**Comment by MansMeg** [comment]
PS Under vägens gång såg jag en enkel fix som stänger issue #77

diff --git a/R/assertion_funcions.R b/R/assertion_funcions.R
index 2921086..455efc4 100644
--- a/R/assertion_funcions.R
+++ b/R/assertion_funcions.R
@@ -57,7 +57,7 @@ assert_function_arguments_in_API <- function(
   
   if(!is.null(lab_file))
     if(!file.exists(lab_file))
-      if(!url_success(lab_file))
+      if(http_error(lab_file))
         stop("Lab file could not be found.")
   
   if(!is.logical(force_get_tests) | !is.logical(quiet))
