### ISSUE TITLE
Old function in testthat (or markmyassignment?). Some Error in mark_my_assignment and others

### ISSUE THREAD

**Issue by oscpe436** [MansMeg/markmyassignment#80]
mark_my_assignment()
Mandatory tests: .1
task1: ...
task2: ...
task2: ....

Failed -----------------------------------------
1. Error: Mandatory tests (@test-00mandatory-1.R#7) 
could not find function "use_package"
1: .handleSimpleError(function (e) 
   {
       e$call <- sys.calls()[(frame + 11):(sys.nframe() - 
           2)]
       register_expectation(e, frame + 11, sys.nframe() - 
           2)
       signalCondition(e)
   }, "could not find function \"use_package\"", quote(eval(expr, 
       envir, enclos))) at C:\Users\User\AppData\Local\Temp\Rtmpgp9Pnq/markmyassignment/assignment1/tests/test-00mandatory-1.R:7
2: eval(expr, envir, enclos)

DONE ===========================================

**Comment by MansMeg** [comment]
Bug can be found in:
https://github.com/MansMeg/markmyassignment/blob/master/inst/extdata/example_mandatory.R

**Comment by MansMeg** [comment]
Fixed
