### ISSUE TITLE
Functions passed to apply family

### ISSUE THREAD

**Issue by krzbar** [MansMeg/markmyassignment#85]
Using e.g. 
lapply(X,mean)
lapply(X,sd)

will generate and error as
Failure: Assignment: cov() (@test-cov-1.R#21) ------------------------------------
`cov` contain global variable(s): mean sd.'cov' contains variables not defined in the function (free variables)

One solution for students could be to force them to explicitly declare environments for everything?

Krzysztof

**Comment by MansMeg** [comment]
Yes. I think that is simpler. Otherwise we need to search through the namespaces. It should work if you just write stats::cov instead.
